# originally from https://gist.github.com/dan-blanchard/7045057
sudo: false
language: python

python:
  - "2.7"
  #- "3.3"
  #- "3.4"
  #- "3.5"

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

# Setup anaconda
before_install:
  # Install miniconda
  # This comes from http://conda.pydata.org/docs/travis.html
  - if [[ "${TRAVIS_PYTHON_VERSION%.*}" == "2" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

# Install packages
install:
  # TODO: Figure out how to read this from requirements.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose 
  # Coverage packages are on the binstar channel which no longer works
  - pip install python-coveralls nose-cov
# TODO: Package 
#  - python setup.py install
 
# Run test
script:
  - coverage run tgo_tests.py
  - coverage run data_handling_tests.py
  - coverage run pure_tests.py
  - coverage run ncomp_tests.py
 
after_success:
  - coveralls --config_file .coveragerc

#TODO: add repo_token for code_climate
# addons:
#    code_climate:
#        repo_token: 
